# Auto-generated by qt-pods.
# This file should be put under version control.
TEMPLATE = subdirs
SUBDIRS = \
    authorization \
    authAdvance \
    finduser \
    htmlView \
    photos
include(pods-subdirs.pri)
